### ISSUE TITLE
Those "ignorethis" files can be use for better

### ISSUE THREAD

**Issue by hahahahacker2009** [StjepanBM1/aquaOS#2]
You should change ignorethis to README.md because it is more useful when keeping empty directory visible

**Comment by StjepanBM1** [comment]
I agree with you,  ignorethis files were mostly used while I was creating folders.

**Comment by VanGutan** [comment]
@StjepanBM1 Use GitHub Desktop. Then you don't need create "ignorethis" files and other test files
