### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [StjepanBM1/aquaOS#4]
Hello! Electro here.
I'm trying to open the website (https://aquaos.stjepanstjepan.repl.co) but it takes me to an blank page! i checked the source code (https://github.com/ringwormGO-organization/ringwormGO-website/tree/main/aquaOS-website) and there actually was code in there. So, is the repl.co site not yet updated?

**Comment by StjepanBM1** [comment]
Website is just a blank space because aquaOS is discontinued it merged with PekOS (my other project) to form ReplexOS.
Hope this help
